name: pnet
channels:
  - plotly
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.8.1
  - astor=0.8.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.weakref=1.0.post1
  - backports_abc=0.5
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cloudpickle=1.2.2
  - cytoolz=0.10.1
  - dask-core=1.2.2
  - decorator=4.4.2
  - enum34=1.1.6
  - freetype=2.9.1
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - futures=3.3.0
  - gast=0.3.3
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - imageio=2.6.1
  - intel-openmp=2019.4
  - ipykernel=4.10.0
  - ipython_genutils=0.2.0
  - jpeg=9b
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libtiff=4.1.0
  - linecache2=1.0.0
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=3.0.5
  - ncurses=6.2
  - numpy=1.16.6
  - numpy-base=1.16.6
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=0.23.4
  - pathlib2=2.3.5
  - pillow=6.2.1
  - pip=18.1
  - plotly=4.5.4
  - plotly-orca=1.2.1
  - prompt_toolkit=1.0.15
  - protobuf=3.11.2
  - pygments=2.5.2
  - python=2.7.15
  - python-dateutil=2.7.5
  - pytz=2019.3
  - pywavelets=1.0.3
  - pyyaml=5.1.1
  - pyzmq=18.1.0
  - readline=7.0
  - retrying=1.3.3
  - scandir=1.10.0
  - scikit-image=0.14.2
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - setuptools=44.0.0
  - singledispatch=3.4.0.3
  - six=1.13.0
  - sqlite=3.31.1
  - subprocess32=3.5.4
  - tensorboard=1.12.2
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=5.1.1
  - traceback2=1.4.0
  - traitlets=4.3.3
  - unittest2=1.1.0
  - wcwidth=0.1.9
  - werkzeug=1.0.0
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - adjusttext=
    - appnope=
    - autograd=
    - autopep8=
    - bottleneck=
    - brokenaxes=
    - certifi=
    - chardet=
    - cycler=
    - future=
    - idna=
    - ipython=
    - ipython-genutils=
    - jinja2=
    - lifelines=
    - markupsafe=
    - matplotlib=
    - networkx=
    - np-utils=
    - pexpect=
    - pickleshare=
    - prompt-toolkit=
    - psutil=
    - ptyprocess=
    - pycodestyle=
    - pygraphviz=
    - pyparsing=
    - pyvis=
    - requests=
    - rope=
    - seaborn=
    - simplegeneric=
    - theano=
    - toml=
    - upsetplot=
    - urllib3=
    - xlrd=

